### ISSUE TITLE
v3 extensions not copied from csr to crt

### ISSUE THREAD

**Issue by gutmensch** [bodsch/ansible-snakeoil#2]
Heyho, thanks for the sweet role! One minor issue I encountered was that the extensions (in this case mostly subjectAltNames) were not copied to the certificate in my openssl version, which defeats much of the purpose of the feature, since CN's are considered outdated for server/host verification:
```
 $ openssl version
OpenSSL 1.1.1m  14 Dec 2021
```
Hence I would suggest the following changes (if they don't break existing older versions, didn't test)
```
diff -ad -uNrp ansible-snakeoil-master/library/snakeoil_openssl.py bodsch.snakeoil-cert/library/snakeoil_openssl.py
--- ansible-snakeoil-master/library/snakeoil_openssl.py 2022-01-05 09:52:29.000000000 +0100
+++ bodsch.snakeoil-cert/library/snakeoil_openssl.py    2022-03-27 17:32:50.547204392 +0200
@@ -99,6 +99,10 @@ class SnakeoilOpenssl(object):
             _ssl_args.append(crt_file)
             _ssl_args.append("-signkey")
             _ssl_args.append(key_file)
+            _ssl_args.append("-extfile")
+            _ssl_args.append(self.openssl_config)
+            _ssl_args.append("-extensions")
+            _ssl_args.append("req_ext")
             _ssl_args.append("-days")
             _ssl_args.append(str(self.cert_life_time))

```
and
```
diff -ad -uNrp ansible-snakeoil-master/tasks/main.yml bodsch.snakeoil-cert/tasks/main.yml
--- ansible-snakeoil-master/tasks/main.yml      2022-01-05 09:52:29.000000000 +0100
+++ bodsch.snakeoil-cert/tasks/main.yml 2022-03-27 17:32:15.873889666 +0200
@@ -107,6 +107,7 @@
         state: crt
         directory: "{{ snakeoil_local_tmp_directory }}"
         domain: "{{ snakeoil_domain }}"
+        openssl_config: "{{ snakeoil_domain }}.conf"
         cert_life_time: "{{ snakeoil_life_time | int }}"

```
to add the extensions also into the certificate. I could possible mess with my own openssl conf or create an own one especially for this role, but I'd argue reusing the existing csr conf is a better solution. Keep up the good work and thanks again!

Cheers,
Robert

**Comment by bodsch** [comment]
Thanx for your Issue!
I will have a look at it as soon as I have time again!

**Comment by bodsch** [comment]
I have opened a corresponding [PR](https://github.com/bodsch/ansible-snakeoil/pull/3).

It would be nice if you could give me an example configuration so that I could integrate it into the tests!

**Comment by gutmensch** [comment]
Thanks a lot for the fix! In terms of configuration I just double checked with your test configuration and to share mine:
```
snakeoil_extract_to: '/etc/ssl'
snakeoil_domain: registry.lan
snakeoil_email: "cert@{{ snakeoil_domain }}"
snakeoil_life_time: 720
snakeoil_alt_names:
  - dns:
    - registry.lan
snakeoil_dhparam: 1024
snakeoil_force: false
snakeoil_dn:
  country: DE
  state: Berlin
  location: Berlin
  organisation: borgkube Inc.
snakeoil_extract_owner: docker-registry
snakeoil_extract_group: root
```
I did too many test runs with involved servers and clients, but I think the root cause was the missing extensions in the resulting certificate (a problem that I also had with own openssl scripts). So this has changed in the openssl defaults from automatically including the v3 extensions to the certificate to later not doing this anymore. So I would just suggest to add a test that runs
```
openssl x509 -noout -text < result.crt | grep -q 'DNS:\|IP:'
```
or some other more programmatic approach. This should have definitely failed before your fix on newer Linux distros. For reference my involved servers were:
```
ansible host: Arch Linux /Manjaro 21.2.6 (Qonos) (OpenSSL 1.1.1m  14 Dec 2021)
target host: Ubuntu 20.04 (OpenSSL 1.1.1f  31 Mar 2020)
```
Cheers and thanks again!
